import { useEffect, useState } from "react";

const resumeUrl = "https://drive.google.com/file/d/1FQ-h7Tb5Op4GAJKssepErxSD2EhhJ38E/view?usp=sharing";
const profileImage = "/assets/img/links/WhatsApp Image 2025-04-26 at 12.27.24 AM.jpeg";
const navItems = [["Home", "header"], ["Profile", "about"], ["Journey", "education"], ["Experience", "experience"], ["Builds", "portfolio"], ["Stack", "skills"], ["Connect", "links"]];
const projects = [
  { id: "svc_01", name: "YouTube Ad View Prediction", type: "DATA PIPELINE", summary: "A regression service that cleans video metrics, extracts useful signals, and predicts ad performance.", stack: ["Python", "Pandas", "Scikit-learn"], image: "https://static.wixstatic.com/media/a8fa06_147d4597a01c4729a8fae21fbf35a0d5~mv2.jpg/v1/crop/x_208,y_0,w_1632,h_2048/fill/w_850,h_798,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Gemini_Generated_Image_62qu3d62qu3d62qu.jpg", link: "https://drive.google.com/file/d/1wqKLswU76nesPbC_6Ur3XmyDttJZ_JTz/view?usp=sharing", details: "A machine learning model trained on metrics from around 15,000 videos, including views, likes, comments, duration, category, and published date." },
  { id: "svc_02", name: "FinTrack Finance Dashboard", type: "TRANSACTION SYSTEM", summary: "A client-side finance system with persistent storage, category filters, and spending visualizations.", stack: ["JavaScript", "Chart.js", "Local Storage"], image: "https://static.wixstatic.com/media/a8fa06_90364b05933444df962c0f6d9a178600~mv2.jpg/v1/crop/x_208,y_0,w_1632,h_2048/fill/w_816,h_808,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Gemini_Generated_Image_pmvzt6pmvzt6pmvz.jpg", link: "https://nikesh-12215759.github.io/Expense-Tracker/", details: "A real-time expense tracker with local persistence, category-wise filtering, and interactive charts for spending patterns." },
  { id: "svc_03", name: "Allen Solly Sales Dashboard", type: "ANALYTICS SERVICE", summary: "An interactive reporting layer for category, regional, and annual sales performance.", stack: ["Excel", "Data Modeling", "Dashboarding"], image: "https://static.wixstatic.com/media/a8fa06_f826bc70b4834bd791390ee793e67369~mv2.jpg/v1/crop/x_104,y_0,w_816,h_1024/fill/w_816,h_792,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/Allen%20Solly%20Sales%20Dashboard.jpg", link: "https://www.linkedin.com/posts/nikeshsahoo_fashionforward-allensollysales-activity-7185311843907710976-WhE7", details: "An interactive Excel dashboard visualizing annual sales trends, top-performing categories, and regional performance." },
];
const skillGroups = [{ title: "LANGUAGES", items: ["JavaScript", "Python", "Java", "SQL"] }, { title: "BACKEND", items: ["Node.js", "Express.js", "REST APIs", "MongoDB"] }, { title: "DATA", items: ["MySQL", "PostgreSQL", "Pandas", "Scikit-learn"] }, { title: "INFRASTRUCTURE", items: ["Git", "Docker", "Kubernetes", "AWS"] }];

function Section({ id, number, label, title, children }) {
  return <section id={id} className="section"><div className="section-frame"><div className="section-heading"><span className="section-number">{number}</span><div><p className="eyebrow">{label}</p><h2>{title}</h2></div></div>{children}</div></section>;
}

function DetailView({ project, contact = false, onBack }) {
  const [sent, setSent] = useState(false);
  if (contact) return <div className="detail-page"><div className="detail-top"><button className="back-link" onClick={onBack}>← BACK TO PROFILE</button><span>ENDPOINT / CONTACT</span></div><div className="detail-content contact-detail"><p className="eyebrow">POST /contact/nikesh</p><h1>Start a<br /><em>conversation.</em></h1><p>Tell me what you are building, what is breaking, or what could be made more useful.</p>{sent ? <div className="success-message"><span>201</span><strong>REQUEST QUEUED</strong><small>Thanks for reaching out. I&apos;ll get back to you soon.</small></div> : <form onSubmit={(event) => { event.preventDefault(); setSent(true); }}><label>Name<input required name="name" /></label><label>Email<input required type="email" name="email" /></label><label>Message<textarea required name="message" rows="5" /></label><button className="primary-button" type="submit">Send request ↗</button></form>}<div className="social-row"><a href="https://github.com/Nikesh-12215759" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/nikeshsahoo/" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></div>;
  return <div className="detail-page"><div className="detail-top"><button className="back-link" onClick={onBack}>← BACK TO PROFILE</button><span>{project.id} / DETAIL</span></div><div className="detail-content"><p className="eyebrow">{project.type}</p><h1>{project.name}</h1><div className="detail-grid"><img src={project.image} alt={project.name} /><div><p className="lead">{project.summary}</p><p>{project.details}</p><div className="stack-row">{project.stack.map((item) => <span key={item}>{item}</span>)}</div><a className="primary-button" href={project.link} target="_blank" rel="noreferrer">Open live resource ↗</a></div></div></div></div>;
}

function App() {
  const [active, setActive] = useState(window.location.hash.slice(1) || "header");
  const [menuOpen, setMenuOpen] = useState(false);
  const [online, setOnline] = useState(true);
  const [typed, setTyped] = useState("");
  const phrases = ["backend developer", "API builder", "data systems thinker"];

  useEffect(() => {
    let phraseIndex = 0; let position = 0; let deleting = false;
    const timer = setInterval(() => { const phrase = phrases[phraseIndex]; position += deleting ? -1 : 1; setTyped(phrase.slice(0, position)); if (position >= phrase.length) deleting = true; if (deleting && position === 0) { deleting = false; phraseIndex = (phraseIndex + 1) % phrases.length; } }, 105);
    const pulse = setInterval(() => setOnline((value) => !value), 3600);
    return () => { clearInterval(timer); clearInterval(pulse); };
  }, []);

  const goTo = (id) => { setActive(id); setMenuOpen(false); window.history.replaceState(null, "", `#${id}`); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  const route = window.location.hash.slice(1);
  const detailProject = route.startsWith("project/") ? projects.find((project) => project.id === route.split("/")[1]) : null;
  if (detailProject || route === "contact") return <DetailView project={detailProject} contact={route === "contact"} onBack={() => { window.history.replaceState(null, "", "#header"); window.location.reload(); }} />;

  return <div className="app-shell">
    <header id="header" className="hero"><div className="grid-overlay" /><nav className="topbar"><a className="brand" href="#header" onClick={() => goTo("header")}>nikesh<span>.dev</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? "CLOSE" : "MENU"}</button><div className={`nav-links ${menuOpen ? "open" : ""}`}>{navItems.map(([label, id]) => <button key={id} className={active === id ? "active" : ""} onClick={() => goTo(id)}>{label}</button>)}</div><a className="resume-button" href={resumeUrl} target="_blank" rel="noreferrer">Resume <span>↗</span></a></nav><div className="hero-layout"><div className="hero-copy"><p className="terminal-line"><i className={online ? "online" : ""} /> system.status = {online ? "200 OK" : "reconnecting..."}</p><p className="eyebrow">BACKEND ENGINEER / DATA BUILDER</p><h1>Systems that<br /><em>hold up.</em></h1><p className="intro">I&apos;m a <strong>{typed}</strong><b className="cursor">|</b>. I design reliable services, useful data flows, and the calm interfaces that make complex systems easier to use.</p><div className="hero-actions"><button className="primary-button" onClick={() => goTo("portfolio")}>Inspect my builds <span>↓</span></button><a className="text-link" href="https://github.com/Nikesh-12215759" target="_blank" rel="noreferrer">github ↗</a></div></div><div className="system-panel"><div className="panel-top"><span>LOCAL / PROFILE</span><span>v1.0.0</span></div><div className="architecture"><div className="node node-main"><span>01</span><strong>nikesh.dev</strong><small>APPLICATION LAYER</small></div><div className="connector" /><div className="node"><span>02</span><strong>API</strong><small>REST / SERVICES</small></div><div className="connector" /><div className="node"><span>03</span><strong>DATA</strong><small>SQL / ML</small></div></div><div className="panel-log"><p><span>GET</span> /about <b>200</b></p><p><span>GET</span> /projects <b>200</b></p><p><span>POST</span> /build/future <b className="amber">202</b></p></div></div></div><div className="hero-footer"><span>ODISHA, INDIA / IST</span><span>SCROLL TO QUERY ↓</span><span>01—07</span></div></header>
    <main>
      <Section id="about" number="01" label="IDENTITY / PROFILE" title="More than a feature list."><div className="about-layout"><div className="portrait-wrap"><img src={profileImage} alt="Nikesh Sahoo" /><span>PROFILE_IMAGE<br />STATUS: LOADED</span></div><div className="about-copy"><p className="lead">I care about what happens behind the screen.</p><p>My work sits at the intersection of backend engineering and data science. I build the logic, APIs, and data layers that turn an idea into a dependable product.</p><p>From Python models and SQL queries to Node.js services and containerized workflows, I enjoy making the invisible parts of software feel intentional.</p><div className="metric-row"><div><b>250+</b><small>PROBLEMS SOLVED</small></div><div><b>3</b><small>CORE BUILDS</small></div><div><b>∞</b><small>QUESTIONS ASKED</small></div></div></div></div></Section>
      <Section id="education" number="02" label="FOUNDATION / LOG" title="The learning layer."><div className="log-list"><article><span className="log-index">[01]</span><div><small>2022 — PRESENT / LPU</small><h3>B.Tech. Computer Science & Engineering</h3><p>Algorithms, data structures, databases, modular programming, and web development.</p></div><b className="log-state">ACTIVE</b></article><article><span className="log-index">[02]</span><div><small>2020 — 2022 / SCIENCE</small><h3>Higher Secondary Education</h3><p>Physics, chemistry, mathematics, English, and Python programming.</p></div><b className="log-state">COMPLETE</b></article></div></Section>
      <Section id="experience" number="03" label="RUNTIME / EXPERIENCE" title="Learning in production."><div className="experience-layout"><div className="experience-summary"><p className="lead">Every role is a new environment to debug.</p><p>Internships, open-source work, and coding practice have trained me to break large problems into small, observable systems.</p></div><div className="timeline"><article><small>05.2024 — 07.2024 / INTERNSHIP STUDIO</small><h3>Machine Learning Intern</h3><p>Built a YouTube ad-view prediction model, handled data cleaning and feature discovery, and improved results through regression tuning.</p><a href="https://drive.google.com/file/d/1HTlP3YxAT1MiTm2HczfkYXGCnEA5enPD/view?usp=sharing" target="_blank" rel="noreferrer">REPORT_FILE ↗</a></article><article><small>04.2025 / DEVFOLIO</small><h3>Front-End & Back-End Guru</h3><p>Recognized for building responsive applications and scalable server-side systems during hackathon and project work.</p><a href="https://devfolio.co/badges" target="_blank" rel="noreferrer">BADGES ↗</a></article><article><small>2023 — PRESENT / LEETCODE</small><h3>Daily algorithm practice</h3><p>250+ problems across arrays, graphs, recursion, dynamic programming, and complexity analysis.</p><a href="https://leetcode.com/u/Nikesh_sahoo/" target="_blank" rel="noreferrer">PROFILE ↗</a></article></div></div></Section>
      <Section id="portfolio" number="04" label="SERVICES / BUILDS" title="Things I&apos;ve shipped."><div className="project-grid">{projects.map((project) => <article className="project-card" key={project.id}><div className="project-head"><span>{project.id}</span><small>{project.type}</small></div><div className="project-image"><img src={project.image} alt={project.name} /></div><div className="project-info"><h3>{project.name}</h3><p>{project.summary}</p><div className="stack-row">{project.stack.map((item) => <span key={item}>{item}</span>)}</div><a href={`#project/${project.id}`}>Inspect service ↗</a></div></article>)}</div></Section>
      <Section id="skills" number="05" label="DEPENDENCIES / STACK" title="The machinery I use."><div className="skill-grid">{skillGroups.map((group, index) => <article key={group.title}><span className="skill-index">0{index + 1}</span><h3>{group.title}</h3><div>{group.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></Section>
      <Section id="links" number="06" label="ENDPOINT / CONTACT" title="Send a request."><div className="contact-layout"><div><p className="lead">Have a problem worth solving?</p><p>Drop a line. I&apos;m always interested in useful products, thoughtful teams, and systems that can be made better.</p></div><a className="contact-terminal" href="#contact"><span>$ curl -X POST</span><strong>/contact/nikesh</strong><b>EXECUTE ↗</b></a></div><div className="social-row"><a href="https://github.com/Nikesh-12215759" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/nikeshsahoo/" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={resumeUrl} target="_blank" rel="noreferrer">Resume ↗</a></div></Section>
    </main><footer><span>nikesh.dev / build 2025</span><span>STATUS: READY FOR THE NEXT REQUEST</span><span>06—07</span></footer>
  </div>;
}

export default App;
